# Generated by Django 3.1.2 on 2020-10-30 18:47

from django.db import migrations, models
import estados.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
                ('bandeira', models.ImageField(blank=True, null=True, upload_to=estados.models.upload_bandeira_estado)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
