# Generated by Django 3.1.2 on 2020-10-30 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0001_initial'),
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='paises.paises'),
            preserve_default=False,
        ),
    ]
