# Generated by Django 3.1.2 on 2020-10-30 18:33

from django.db import migrations, models
import paises.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('bandeira', models.ImageField(blank=True, null=True, upload_to=paises.models.upload_bandeira_pais)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
