# Generated by Django 3.2.3 on 2021-06-02 14:40

from django.db import migrations, models
import django.db.models.deletion
import torneios.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidades', '0004_cidades_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroCategorias',
            fields=[
                ('generoId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeGenero', models.CharField(max_length=40)),
                ('ativo', models.BooleanField(default=True)),
                ('dataInclusao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelCategorias',
            fields=[
                ('nivelId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeNivel', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('dataInclusao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Torneios',
            fields=[
                ('torneioId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomeTorneio', models.CharField(max_length=100)),
                ('dataInicioInscricao', models.DateField()),
                ('dataTerminoInscricao', models.DateField()),
                ('dataInicioTorneio', models.DateField()),
                ('dataTerminoTorneio', models.DateField()),
                ('local', models.CharField(max_length=80)),
                ('endereco', models.CharField(max_length=120)),
                ('responsavel', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('informacao', models.TextField(max_length=1000, null=True)),
                ('panfleto', models.ImageField(blank=True, null=True, upload_to=torneios.models.upload_panfleto_torneio)),
                ('dataInclusao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now_add=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cidades.cidades')),
            ],
        ),
    ]
