# Generated by Django 3.1.2 on 2020-11-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneios',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='torneios',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='torneios',
            name='uf',
        ),
    ]
