# Generated by Django 3.1.2 on 2020-11-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0004_cidades_estado'),
        ('torneios', '0002_auto_20201113_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneios',
            name='cidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='cidades.cidades'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torneios',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
