# Generated by Django 3.2.3 on 2021-06-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0002_generocategorias_dupla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generocategorias',
            old_name='dupla',
            new_name='somenteDupla',
        ),
    ]
