# Generated by Django 3.2.3 on 2021-06-10 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0005_auto_20210602_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelcategorias',
            name='idadeMaxima',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivelcategorias',
            name='idadeMinima',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
