# Generated by Django 3.2.3 on 2021-06-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0006_auto_20210610_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorneioCategorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroMaximoParticipantes', models.SmallIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('dataInclusao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now_add=True)),
                ('generoCategoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.generocategorias')),
                ('nivelCategoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.nivelcategorias')),
                ('tipoCategoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.tipocategorias')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.torneios')),
            ],
        ),
    ]
