# Generated by Django 3.2.3 on 2021-06-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0008_auto_20210611_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneiocategorias',
            name='generoCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.generocategorias', unique=True),
        ),
        migrations.AlterField(
            model_name='torneiocategorias',
            name='nivelCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.nivelcategorias', unique=True),
        ),
        migrations.AlterField(
            model_name='torneiocategorias',
            name='tipoCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.tipocategorias', unique=True),
        ),
        migrations.AlterField(
            model_name='torneiocategorias',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.torneios', unique=True),
        ),
    ]
