# Generated by Django 3.2.3 on 2021-06-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0009_auto_20210616_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneiocategorias',
            name='generoCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.generocategorias'),
        ),
        migrations.AlterField(
            model_name='torneiocategorias',
            name='nivelCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.nivelcategorias'),
        ),
        migrations.AlterField(
            model_name='torneiocategorias',
            name='tipoCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.tipocategorias'),
        ),
        migrations.AlterField(
            model_name='torneiocategorias',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.torneios'),
        ),
        migrations.AddConstraint(
            model_name='torneiocategorias',
            constraint=models.UniqueConstraint(fields=('torneio', 'tipoCategoria', 'generoCategoria', 'nivelCategoria'), name='categoria_torneio_unica'),
        ),
    ]
