# Generated by Django 3.2.3 on 2021-07-25 01:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0012_auto_20210724_2244'),
        ('torneios', '0010_auto_20210616_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('equipeId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('jogoId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data_jogo', models.DateField()),
                ('hora_jogo', models.TimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='torneiocategorias',
            name='categoria_torneio_unica',
        ),
        migrations.AlterField(
            model_name='torneiocategorias',
            name='generoCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.generocategorias', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='torneiocategorias',
            name='nivelCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.nivelcategorias', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='torneiocategorias',
            name='numeroMaximoParticipantes',
            field=models.SmallIntegerField(verbose_name='Numero Maximo Participantes/Duplas'),
        ),
        migrations.AlterField(
            model_name='torneiocategorias',
            name='tipoCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.tipocategorias', verbose_name='Tipo Categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='torneiocategorias',
            unique_together={('torneio', 'tipoCategoria', 'generoCategoria', 'nivelCategoria')},
        ),
        migrations.AddField(
            model_name='equipes',
            name='atleta',
            field=models.ManyToManyField(to='atletas.Atletas'),
        ),
        migrations.AddField(
            model_name='equipes',
            name='torneioCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.torneiocategorias'),
        ),
    ]
