# Generated by Django 3.2.3 on 2021-07-25 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0011_auto_20210724_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipes',
            name='dataAtualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipes',
            name='dataInclusao',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
