# Generated by Django 3.2.3 on 2021-07-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0012_auto_20210724_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipes',
            name='dataAtualizacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipes',
            name='dataInclusao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
