# Generated by Django 3.2.3 on 2021-07-26 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0012_auto_20210724_2244'),
        ('torneios', '0014_alter_equipes_atleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneiocategorias',
            name='id',
        ),
        migrations.AddField(
            model_name='jogos',
            name='equipeA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='torneios.equipes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torneiocategorias',
            name='torneioCategoriaId',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipes',
            name='atleta',
            field=models.ManyToManyField(related_name='atletas', to='atletas.Atletas', verbose_name='Atleta(s)'),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='jogoId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
