# Generated by Django 3.2.3 on 2021-07-26 19:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0015_auto_20210726_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='equipeB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipeB', to='torneios.equipes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jogos',
            name='equipeA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipeA', to='torneios.equipes'),
        ),
    ]
