# Generated by Django 3.2.3 on 2021-07-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0016_auto_20210726_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torneiocategorias',
            options={'managed': False},
        ),
    ]
