# Generated by Django 3.2.3 on 2021-07-26 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0017_alter_torneiocategorias_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torneiocategorias',
            options={},
        ),
        migrations.AddField(
            model_name='jogos',
            name='dataAtualizacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogos',
            name='dataInclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
