# Generated by Django 3.2.3 on 2021-07-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneios', '0018_auto_20210726_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogos',
            old_name='data_jogo',
            new_name='dataJogo',
        ),
        migrations.RenameField(
            model_name='jogos',
            old_name='hora_jogo',
            new_name='horaJogo',
        ),
    ]
