# Generated by Django 3.1.2 on 2020-11-06 21:49

import cidades.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('bandeira', models.ImageField(blank=True, null=True, upload_to=cidades.models.upload_bandeira_pais)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
                ('bandeira', models.ImageField(blank=True, null=True, upload_to=cidades.models.upload_bandeira_estado)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cidades.paises')),
            ],
        ),
    ]
