# Generated by Django 3.1.2 on 2020-11-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0002_paises_sigla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('cidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=3)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_modificacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
