# Generated by Django 3.1.2 on 2020-11-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0003_cidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidades',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='cidades.estados'),
            preserve_default=False,
        ),
    ]
