# Generated by Django 3.1.2 on 2020-10-29 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atletas',
            fields=[
                ('atleta_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('data_inclusao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Atleta',
        ),
    ]
