# Generated by Django 3.1.2 on 2020-10-29 19:58

import atletas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0002_auto_20201029_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='atletas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=atletas.models.upload_foto_atleta),
        ),
    ]
