# Generated by Django 3.1.2 on 2020-10-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0003_atletas_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atletas',
            name='apelido',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atletas',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='atletas',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
