# Generated by Django 3.1.2 on 2020-10-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_auto_20201029_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='atletas',
            name='sobrenome',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atletas',
            name='apelido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atletas',
            name='nome',
            field=models.CharField(max_length=60),
        ),
    ]
