# Generated by Django 3.1.2 on 2020-10-30 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0005_auto_20201029_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='atletas',
            name='data_ultima_modificacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atletas',
            name='data_inclusao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
