# Generated by Django 3.1.2 on 2020-11-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0006_auto_20201030_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atletas',
            name='apelido',
            field=models.CharField(default='app', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atletas',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
