# Generated by Django 3.1.2 on 2020-11-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0007_auto_20201107_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atletas',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
