# Generated by Django 3.1.2 on 2020-11-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0008_auto_20201107_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='atletas',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
