# Generated by Django 3.1.2 on 2020-11-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0004_cidades_estado'),
        ('atletas', '0009_atletas_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atletas',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='cidades.cidades'),
            preserve_default=False,
        ),
    ]
