# Generated by Django 3.2.3 on 2021-07-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0011_auto_20210524_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atletas',
            old_name='atleta_id',
            new_name='atletaId',
        ),
        migrations.RenameField(
            model_name='atletas',
            old_name='data_atualizacao',
            new_name='dataAtualizacao',
        ),
        migrations.RenameField(
            model_name='atletas',
            old_name='data_inclusao',
            new_name='dataInclusao',
        ),
        migrations.RenameField(
            model_name='atletas',
            old_name='data_nascimento',
            new_name='dataNascimento',
        ),
    ]
